FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

RUN addgroup --system django \
    && adduser --system --ingroup django django

COPY start-web.sh /
RUN chmod +x /start-web.sh
RUN chown django /start-web.sh

COPY test.sh /
RUN chmod +x /test.sh
RUN chown django /test.sh

COPY --chown=django:django . /app

USER django

WORKDIR /app

CMD ["bash", "/start-web.sh"]